
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `icts_desafio` DEFAULT CHARACTER SET utf8 ;
USE `icts_desafio` ;

DROP TABLE IF EXISTS `icts_desafio`.`Compra` ;

CREATE TABLE IF NOT EXISTS `icts_desafio`.`Compra` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `total` DOUBLE NOT NULL,
  `data_criacao` DATE NOT NULL,
  `tipo_pagamento` VARCHAR(10) NOT NULL,
  `status` CHAR(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


DROP TABLE IF EXISTS `icts_desafio`.`Produto` ;

CREATE TABLE IF NOT EXISTS `icts_desafio`.`Produto` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(300) NOT NULL,
  `preco` DOUBLE NOT NULL,
  `data_criacao` DATE NOT NULL,
  `data_atualizacao` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

